name: Build MKS TinyBee Marlin Firmware

on:
  push:
    branches:
      - main
    #paths:
    #  - 'Firmware/Configuration/**.h'
  
  workflow_dispatch:

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest
    env:
      BOARD: mks_tinybee
      
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Compile firmware
        run: |
          docker run \
            -u root:root \
            -e BOARD \
            -e UPDATE_FORCE=true \
            -e USE_BRANCH=BrailleRAP \
            -e FW_EXTENSION=bin \
            -v $(pwd)/Firmware/builds:/home/platformio/build \
            -v $(pwd)/Firmware/configuration/MKSTinyBee:/home/platformio/CustomConfiguration \
            sgngodin/braillerap-marlin-build:latest
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: mks_tinybee
          path: Firmware/builds/mks_tinybee/*.bin
      
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '6 month' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
          # Optional inputs
          # skip-tags: true
          skip-recent: 2
     